version: "v1.21.0+k3s1"
image: "generic/alpine312"
token: "agent-token"
ip_range: "10.0.0."
interface: "eth1"
masters:
  count: 2
  resources:
    memory: "2048"
    cpu: "2"
workers:
  count: 4
  resources:
    memory: "1024"
    cpu: "1"
lb:
  ip: "10.0.0.30"
  resources:
    memory: "512"
    cpu: "1"
local_registry:
  enabled: true
  port: 30500
  host: "localregistry.lc"
