version: "v1.21.0+k3s1"
image: "generic/alpine312"
token: "agent-token"
ip_range: "10.0.0."
interface: "eth1"
masters:
  count: 3
  resources:
    memory: "2048"
    cpu: "2"
workers:
  count: 3
  resources:
    memory: "1024"
    cpu: "1"
lb:
  id: 30
  resources:
    memory: "512"
    cpu: "1"
